title: <p align="center"> Vasu teotia </p>


description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/sajan-kedia-b06a6821/">LinkedIn</a> |
  <a href="https://github.com/sajankedia">GitHub</a>
  
  <br>   
  I'm working on Data Science, Machine learning & NLP related problems.
  Also handing the Big Data from real-time Ad call data.
  Working in the Health Insurance domain for 3 years.
  <br>
  </p>



theme: jekyll-theme-minimal
